name: Deploy to Hostinger via SFTP (SSH Key)

on:
  push:
    branches:
      - main

jobs:
  # O job 'deploy' começa aqui, sem espaços.
  deploy:
    # 'runs-on' tem dois espaços.
    runs-on: ubuntu-latest

    # 'steps' também tem dois espaços.
    steps:
      # O '-' do passo começa com quatro espaços.
      - name: Checkout code
        uses: actions/checkout@v3

      # Este é o passo de teste que adicionamos.
      - name: Print Runner IP address
        run: echo "O endereço de IP deste servidor é:" && curl -s ifconfig.me

      # O próximo passo, também começa com quatro espaços.
      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v5.0.0
        # 'with:' tem seis espaços.
        with:
          # Cada parâmetro dentro do 'with' tem oito espaços.
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          SOURCE: "build/" # Ou "dist/"
          TARGET: "public_html"
          ARGS: "--delete"
