# Nome do workflow atualizado
name: Deploy to Hostinger via SFTP

# Gatilho: Roda em todo push na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório (incluindo a pasta 'build')
      - name: Checkout code
        uses: actions/checkout@v3

        # ... (passo 'Checkout code' fica aqui em cima)

      # NOVO PASSO PARA DESCOBRIR O IP
      - name: Print Runner IP address
        run: echo "O endereço de IP deste servidor é:" && curl -s ifconfig.me

      # O PASSO DE DEPLOY VEM DEPOIS
      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v5.0.0
        # ... (o resto do seu código de deploy)

      # 2. Deploy para Hostinger usando a Action correta para SFTP/SSH
      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v5.0.0 # <<< Usando a nova Action
        with:
          # Credenciais (reutilizando os Secrets que você já criou)
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Pode deixar assim mesmo que não use chave
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PASSWORD: ${{ secrets.FTP_PASSWORD }}

          # Pastas de origem e destino
          SOURCE: "build/" # <<< MUITO IMPORTANTE: Mude para "dist/" se seu projeto usar 'dist'.
          TARGET: "public_html"

          # Opção para excluir arquivos no destino que não existem na origem (limpa a build antiga)
          ARGS: "--delete"
